### ISSUE TITLE
Username is sometimes requested twice

### ISSUE THREAD

**Issue by tomisaacson** [aws-azure-login/aws-azure-login#62] opened 2019-02-17 21:40 UTC
I'm using Ubuntu 18.04 and occasionally when I request a profile I get asked for the username twice:
```
$ aws-azure-login --profile myprofile
Logging in with profile 'myprofile'...
? Username: me@myemail.com
? Username: me@myemail.com
Please enter your password.
? Password: [hidden]
```
It's annoying because if I don't spot this I type my password in the second username prompt and it appears as clear text.

**Comment by davepattie** [comment] 2019-12-11 13:24
This is probably caused by passwordless MFA auth where it's popping up on the screen a number for you to confirm with your phone.  This is the same behaviour I get with this issue - https://github.com/sportradar/aws-azure-login/issues/52 but that's not received a response either

**Comment by kennethaasan** [comment] 2019-12-11 23:38
Definitely looks like the same problem. Closing this in favor of #52

**Closed as completed by kennethaasan** 2019-12-11 23:38 UTC
