### ISSUE TITLE
Launching browser fails on Apple Silicon

### ISSUE THREAD

**Issue by slaffcheff** [aws-azure-login/aws-azure-login#181] opened 2021-04-09 16:04 UTC
Steps to reproduce

OS: macOS Big Sur 11.2.2
Node: v15.12.0
puppeteer@8.0.0

Install the package and it fails with chromium error. You need to install chromium via brew manually and point at zshrc:
```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
```

When I try to run:
`aws-azure-login --mode=gui
`
```
Logging in with profile 'default'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/homebrew/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/aws-azure-login/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (node:events:369:20)
    at ChildProcess.emit (node:domain:470:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

There are some suggestions here: https://github.com/puppeteer/puppeteer/issues/6622
Please, fix this asap since it's a huge blocker for the people with M1.

**Comment by kennethaasan** [comment] 2021-04-09 17:53
Hi, this seems like a duplicate of https://github.com/sportradar/aws-azure-login/issues/166

Please continue the discussion there. It would be great with a PR that solves this because I don't have a computer with Apple Silicon.

Thanks,
Kenneth

**Closed as completed by kennethaasan** 2021-04-09 17:53 UTC
